export const EQ = 'EQ'; // 0000 EQ Z set equal
export const NE = 'NE'; // 0001 NE Z clear not equal
export const CS = 'CS'; // 0010 CS C set unsigned higher or same
export const CC = 'CC'; // 0011 CC C clear unsigned lower
export const MI = 'MI'; // 0100 MI N set negative
export const PL = 'PL'; // 0101 PL N clear positive or zero
export const VS = 'VS'; // 0110 VS V set overflow
export const VC = 'VC'; // 0111 VC V clear no overflow
export const HI = 'HI'; // 1000 HI C set and Z clear unsigned higher
export const LS = 'LS'; // 1001 LS C clear or Z set unsigned lower or same
export const GE = 'GE'; // 1010 GE N equals V greater or equal
export const LT = 'LT'; // 1011 LT N not equal to V less than
export const GT = 'GT'; // 1100 GT Z clear AND (N equals V) greater than
export const LE = 'LE'; // 1101 LE Z set OR (N not equal to V) less than or equal
export const AL = 'AL'; // 1110 AL (ignored) always