import { OpCode } from '../../types/mnemonics/op-codes';
import {
  AND,
  SUB,
  RSB,
  ADD,
  ADC,
  SBC,
  RSC,
  TST,
  TEQ,
  CMP,
  CMN,
  ORR,
  MOV,
  BIC,
  MVN,
  B,
  BL,
  SVC,
  LDR,
  LDRB,
  STRB,
  STR,
  STM,
  LDM,
  BX,
  PUSH,
  POP,
  MUL,
} from '../codes/op-codes';
import {
  AND as AND_NAME,
  B as B_NAME,
  BL as BL_NAME,
  BX as BX_NAME,
  ADD as ADD_NAME,
  CMP as CMP_NAME,
  LDR as LDR_NAME,
  LDRB as LDRB_NAME,
  MOV as MOV_NAME,
  STRB as STRB_NAME,
  STR as STR_NAME,
  SVC as SVC_NAME,
  SUB as SUB_NAME,
  STM as STM_NAME,
  LDM as LDM_NAME,
  PUSH as PUSH_NAME,
  POP as POP_NAME,
  MUL as MUL_NAME,
} from '../mnemonics/op-codes';

export const OpCodeNameToCode: Record<OpCode, number> = {
  [AND_NAME]: AND,
  [SUB_NAME]: SUB,
  RSB: RSB,
  [ADD_NAME]: ADD,
  ADC: ADC,
  SBC: SBC,
  RSC: RSC,
  TST: TST,
  TEQ: TEQ,
  [CMP_NAME]: CMP,
  CMN: CMN,
  ORR: ORR,
  [MOV_NAME]: MOV,
  BIC: BIC,
  MVN: MVN,
  [B_NAME]: B,
  [BL_NAME]: BL,
  [BX_NAME]: BX,
  [SVC_NAME]: SVC,
  [LDR_NAME]: LDR,
  [LDRB_NAME]: LDRB,
  [STRB_NAME]: STRB,
  [STR_NAME]: STR,
  [STM_NAME]: STM,
  [LDM_NAME]: LDM,
  [PUSH_NAME]: PUSH,
  [POP_NAME]: POP,
  [MUL_NAME]: MUL,
};
