export const EQ = 0x0; // 0000 EQ Z set equal
export const NE = 0x1; // 0001 NE Z clear not equal
export const CS = 0x2; // 0010 CS C set unsigned higher or same
export const CC = 0x3; // 0011 CC C clear unsigned lower
export const MI = 0x4; // 0100 MI N set negative
export const PL = 0x5; // 0101 PL N clear positive or zero
export const VS = 0x6; // 0110 VS V set overflow
export const VC = 0x7; // 0111 VC V clear no overflow
export const HI = 0x8; // 1000 HI C set and Z clear unsigned higher
export const LS = 0x9; // 1001 LS C clear or Z set unsigned lower or same
export const GE = 0xa; // 1010 GE N equals V greater or equal
export const LT = 0xb; // 1011 LT N not equal to V less than
export const GT = 0xc; // 1100 GT Z clear AND (N equals V) greater than
export const LE = 0xd; // 1101 LE Z set OR (N not equal to V) less than or equal
export const AL = 0xe; // 1110 AL (ignored) always
